### Teste de integração com n8n
GET https://zezim123.app.n8n.cloud/webhook-test/0f8dfe703-2b9c-49f0-9004-a27790505bae

### Enviar dados para o n8n
POST https://zezim123.app.n8n.cloud/webhook-test/0f8dfe703-2b9c-49f0-9004-a27790505bae
Content-Type: application/json

{
  "mensagem": "Olá do VS Code!"
}
