name: CI/CD - Build e Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar checagem de ambiente
        run: |
          python tools/check_env.py

      - name: Rodar testes (se existirem)
        run: |
          if [ -d tests ]; then pytest tests/; fi

  # Exemplo de deploy: criar artefato zip do app
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Empacotar app
        run: |
          zip -r baixarMusicas.zip . -x '*.git*' '*.venv*' '*.pytest_cache*' '*.mypy_cache*' '*.env*' '*.log*' '*.pyc' '*__pycache__*'

      - name: Publicar artefato
        uses: actions/upload-artifact@v4
        with:
          name: baixarMusicas-build
          path: baixarMusicas.zip

# Para deploy real (ex: releases, servidores), personalize conforme sua necessidade.
